apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ElevatorControl
  namespace: ElevatorControl
spec:
  template:
    spec:
      containers:
        - image: gitlab.mn8.ee:4567/dev/ElevatorControl:0.0.1
          imagePullPolicy: Always
          env:
            - name: KAFKA_BOOTSTRAP_SERVER
              value: "my-cluster-kafka-bootstrap.kafka:9092"
            - name: ELASTIC_SERVER
              value: "elastic-master-0.elastic-master-headless.elastic-stack.svc.cluster.local"
            - name: ELASTIC_PORT
              value: "9200"
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: password
            - name: JKS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: jksPassword
            - name: ROUTES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: routesauth
                  key: password


---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
data:
  username: ZWxhc3RpYw==
  password: TDFhWHFjYXZEYVlnajNJUzM2ZzE=
  jksPassword: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: routesauth
type: Opaque
data:
  password: cGEyODIxOXcwcmQ=
